### ISSUE TITLE
hotspot broken after script. 

### ISSUE THREAD

**Issue by pedrazadixon** [mattreecebentley/win10_simplifier#1]
my hotspot is broken after script.
any way to fix this?

Thanks in advanced.

**Comment by mattreecebentley** [comment]
If you're running the blackviper services stuff as part of the script, you should know that it by default, turns the wlan service to Manual on desktop machines. I need to fix this, but it's a matter of having time.
If that's the case if you set it to Automatic, your hotspot should be fixed.

If you're not running the blackviper (madbomb) services stuff let me know

**Comment by pedrazadixon** [comment]
yes, I use blackviper as part of the script excecution. 
I change WlanSvc service to Auto and start this, but this not work (reboot pc and not work).

**Comment by pedrazadixon** [comment]
Ok, I solve this: 
1. Set WlanSvc service to automatic and start it. 
2. Set icssvc service to manual.

Hotspot now working for me.

**Comment by mattreecebentley** [comment]
Good to know - please report this to the blackviper madbomb guy, as he's reluctant to make changes (even though I've reported this problem) - the 'safe' setting should actually be safe!
