### ISSUE TITLE
quick access folders in explorer is removed how to restore it back

### ISSUE THREAD

**Issue by jgera** [mattreecebentley/win10_simplifier#3]
After running the __Win10_simplifier.bat, quick access folders in explorer was deleted.
I have tried almost every solution published online but i am unable to solve this. Please help.

Thank you.

**Comment by mattreecebentley** [comment]
See .reg file added to repo today - cheers

**Comment by jgera** [comment]
thanks, by setting hubmode = 0 did the job.

**Comment by mattreecebentley** [comment]
Ah, thanks for that, will fix the .reg file
