### ISSUE TITLE
Can you add this optional app?

### ISSUE THREAD

**Issue by Fedess1986** [mattreecebentley/win10_simplifier#4]
Can you add ThrottleStop, as optional?
If the files .exe and .ini are in the folder maybe they could be copied to c:\program files and created the task scheduler (with high privileges) to run at startup. Would be great if it can be done. Thanks!

**Comment by mattreecebentley** [comment]
Sorry, but I only include apps that I myself might use - but doing this yourself is trivial, so just create your own fork.
Having looked at the app it's not something I would use on the bulk of computers.
